/*
 * What each browser-rendered output in the tree was rendered FROM, so that an
 * output whose inputs have moved on cannot sit in the tree looking current:
 *
 *   node tools/regression/rendered-from.ts --check   fail if any of them is stale
 *
 * Three things in this repository are produced by a browser and committed,
 * because `npm run check` has no browser and has to stay fast and offline:
 *
 *   preview:theme   docs/preview/<language>.png, hero.png, palettes.png
 *   preview:icons   docs/preview/icons-files.png, icons-folders.png
 *   measure         tools/icons/glyph-bounds.json, tools/icons/text-bounds.json
 *
 * The inventory pins the screenshots by their own hash, which catches a picture
 * that changed. It cannot catch a picture that SHOULD have changed and did not
 * — a theme colour moved and nobody re-ran the previews, a pictogram was
 * redrawn and nobody re-measured it, so the build went on placing the new
 * drawing by the old one's ink. Each producer below therefore names the inputs
 * its output is a function of, and records their hash in
 * tools/regression/rendered-from.json when it writes the output. The check
 * recomputes the hash from the tree and refuses one that differs.
 *
 * The inputs are hashed as CONTENT where a file would say too much: the
 * measurement depends on the drawings and the lettering runs, not on every
 * line of tools/icons/icon-spec.ts, so a mapping added to the spec does not
 * ask for a re-measure that would change nothing. Rendering the same inputs
 * twice writes the same bytes (checked when this was written: every preview
 * regenerated byte for byte), so a re-run on unchanged inputs is free.
 *
 * What no hash can see is the renderer itself — an updated Edge, a font that
 * changed under the lettering. That is what `npm run regression` is for: it
 * renders and measures again and compares the pixels and the numbers.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { sha256 } from '../shared/hash.ts';
import { glyphs, NO_SURFACE, type GlyphName } from '../icons/glyphs.ts';
import { marks, type MarkName } from '../icons/marks.ts';
import { FONT_STACK, FONT_WEIGHT, letteringRuns, textMetricsKey, type LetteringRun } from '../icons/icon-spec.ts';

const HERE: string = path.dirname(fileURLToPath(import.meta.url));
const ROOT: string = path.join(HERE, '..', '..');
const RECORD_FILE: string = path.join(HERE, 'rendered-from.json');

export type Producer = 'preview:theme' | 'preview:icons' | 'measure';

/** How to bring a stale output up to date. */
const RERUN: Record<Producer, string> = {
  'preview:theme': 'npm run preview:theme',
  'preview:icons': 'npm run preview:gallery',
  measure: 'npm run measure:glyphs && npm run build:icons && npm run audit:icons',
};

const filesIn = (...directory: string[]): string[] =>
  fs
    .readdirSync(path.join(ROOT, ...directory))
    .sort()
    .map((fileName: string): string => path.join(...directory, fileName));

/** Each input as `name sha256`, one per line, then hashed: the record of what changed is the list itself. */
const hashOfInputs = (inputs: [string, string | Buffer][]): string =>
  sha256(inputs.map(([inputName, content]: [string, string | Buffer]): string => `${inputName} ${sha256(content)}`).join('\n'));

const fileInputs = (files: string[]): [string, Buffer][] =>
  files.map((file: string): [string, Buffer] => [file.replace(/\\/g, '/'), fs.readFileSync(path.join(ROOT, file))]);

const shikiVersion = (): string => JSON.parse(fs.readFileSync(path.join(ROOT, 'node_modules', 'shiki', 'package.json'), 'utf8')).version;

const WHITE: string[] = Array(8).fill('#fff');

const INPUTS: Record<Producer, () => [string, string | Buffer][]> = {
  'preview:theme': (): [string, string | Buffer][] => [
    ...fileInputs([
      path.join('tools', 'preview', 'build-theme-preview.ts'),
      ...filesIn('themes'),
      ...filesIn('tools', 'syntax', 'samples'),
      ...filesIn('injections'),
      ...filesIn('icons', 'theme'),
      ...filesIn('icons', 'svg'),
    ]),
    ['shiki', shikiVersion()],
  ],
  'preview:icons': (): [string, string | Buffer][] =>
    fileInputs([
      path.join('tools', 'preview', 'build-icon-preview.ts'),
      path.join('themes', 'midnight-indigo-color-theme.json'),
      ...filesIn('icons', 'svg'),
    ]),
  /*
   * Exactly what tools/icons/measure.ts draws: every pictogram with and
   * without its surface (which of the two is measured is itself measured),
   * every mark, and every lettering run in the font the icons are set in.
   */
  measure: (): [string, string | Buffer][] => [
    ...fileInputs([path.join('tools', 'icons', 'measure.ts')]),
    ...(Object.keys(glyphs) as GlyphName[]).map((glyphName: GlyphName): [string, string] => [
      `glyph:${glyphName}`,
      glyphs[glyphName](['#fff', '#f00']) + glyphs[glyphName]([WHITE[0], NO_SURFACE]) + glyphs[glyphName](WHITE),
    ]),
    ...(Object.keys(marks) as MarkName[]).map((markName: MarkName): [string, string] => [`mark:${markName}`, marks[markName].draw(WHITE)]),
    [
      'lettering',
      [FONT_STACK, FONT_WEIGHT, ...letteringRuns().map((run: LetteringRun): string => textMetricsKey(run.str, run.size, run.track))].join('\n'),
    ],
  ],
};

export const inputsHash = (producer: Producer): string => hashOfInputs(INPUTS[producer]());

const readRecord = (): Partial<Record<Producer, string>> =>
  fs.existsSync(RECORD_FILE) ? JSON.parse(fs.readFileSync(RECORD_FILE, 'utf8')) : {};

/** Called by a producer once its output is written: these inputs are what it now shows. */
export const recordRendered = (producer: Producer): void => {
  const record: Partial<Record<Producer, string>> = { ...readRecord(), [producer]: inputsHash(producer) };
  const ordered: Partial<Record<Producer, string>> = Object.fromEntries(
    (Object.keys(INPUTS) as Producer[]).filter((name: Producer): boolean => name in record).map((name: Producer) => [name, record[name]])
  );
  fs.writeFileSync(RECORD_FILE, JSON.stringify(ordered, null, 2) + '\n', 'utf8');
};

/** Every producer whose output was rendered from inputs other than the tree's, with the command that brings it up to date. */
export const staleOutputs = (): string[] => {
  const record: Partial<Record<Producer, string>> = readRecord();
  return (Object.keys(INPUTS) as Producer[])
    .filter((producer: Producer): boolean => record[producer] !== inputsHash(producer))
    .map((producer: Producer): string =>
      record[producer]
        ? `${producer} was rendered from inputs that have changed since — run: ${RERUN[producer]}`
        : `${producer} has no record of what it was rendered from — run: ${RERUN[producer]}`
    );
};

const isMain: boolean = process.argv[1] ? path.resolve(process.argv[1]) === fileURLToPath(import.meta.url) : false;

if (isMain && process.argv.includes('--check')) {
  const stale: string[] = staleOutputs();
  for (const problem of stale) console.error(`  ! ${problem}`);
  console.log(stale.length ? `\n${stale.length} rendered output(s) out of date` : 'every rendered output is of the inputs in the tree');
  process.exitCode = stale.length ? 1 : 0;
}
